name: Docker Image CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: "Authenticate to GCP"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: "true"
          project_id: "vernal-mantra-665"
          workload_identity_provider: "projects/67604798339/locations/global/workloadIdentityPools/github-actions/providers/github-actions"

      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 416.0.0"

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        run: |
          docker buildx build \
            -t gcr.io/vernal-mantra-665/medibot:${{ github.ref_name }} \
            -t gcr.io/vernal-mantra-665/medibot:${{ github.sha }} \
            --push --cache-to type=gha,mode=max --cache-from type=gha .
