name: Docker Image CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.your-checkout-token }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: docker buildx build . -t medibot:${{ github.sha }} --cache-to type=gha,mode=max --cache-from type=gha

      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 416.0.0"

      - name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: "true"
          project_id: "vernal-mantra-665"
          workload_identity_provider: "projects/67604798339/locations/global/workloadIdentityPools/github-actions/providers/github-actions"

      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list

      - name: Tag and push image
        run: |
          docker tag medibot gcr.io/vernal-mantra-665/medibot:${{ github.ref_name }}
          docker tag medibot gcr.io/vernal-mantra-665/medibot:build-${{ github.sha }}
          docker push gcr.io/vernal-mantra-665/medibot
